context:
  version: 0.5.1
  python_min: "3.10"

package:
  name: fastembed
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fastembed/fastembed-${{ version }}.tar.gz
    sha256: 93ccdbead9daadde6af37862c53b92fd15fa3115d20bbddb258faa0a5eb36718

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - huggingface_hub <1.0,>=0.20
    - loguru <0.8.0,>=0.7.2
    - mmh3 <5.0.0,>=4.1.0
    - numpy >=2.1.0
    - onnxruntime >1.20.0
    - pillow <11.0.0,>=10.3.0
    - py-rust-stemmers <0.2.0,>=0.1.0
    - requests <3.0,>=2.31
    - tokenizers <1.0,>=0.15
    - tqdm <5.0,>=4.66

tests:
  - python:
      imports:
        - fastembed
      pip_check: true

about:
  homepage: https://github.com/qdrant/fastembed
  summary: Fast, light, accurate library built for retrieval embedding generation
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
